name: drops_app           # your project name
description: "DROPS: Weather + Arduino sensor app"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0               # <-- Needed for OpenWeather API
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  flutter_libserialport: ^0.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/alarm.mp3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0